name: vector
channels:
  - conda-forge
dependencies:
  - jupyterlab >=1.2
  - nb_conda_kernels
  - pip >=18
  - pytest
  - root >=6.18.04
  - numba >=0.50
  - pip:
      - "awkward1>=0.2.29"
      - "uproot==3.*"
      - "scikit-hep-testdata>=0.2.0"
      - -e .
